### ISSUE TITLE
infostring isn't forwarded

### ISSUE THREAD

**Issue by ChristopherBiscardi** [syntax-tree/mdast-util-to-hast#24]
In MDX we'd like to use the infostring as props later in the pipeline, but [mdast-util-to-hast drops it](https://codesandbox.io/s/3y4wymyj75) when doing the [language classname detection for code blocks](https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/handlers/code.js#L12).

Would you accept a PR to forward the raw infostring or the meta string without the detected language in props?

I want to add something like this, which uses the same regex as the lang detection to split the lang off and trim whitespace before forwarding the meta string.

```js
props.metaString = node.lang.replace(/^[^ \t]+(?=[ \t]|$)/, '').trim()
```

The string then shows up directly in props in MDX (and we can also add some handling to turn the string into boolean, etc props before that in our own code).

```jsx
<MDXTag
        name="code"
        components={components}
        parentName="pre"
        props={{ className: "language-js", metaString: "repl" }}
      >{`const t = 1
`}</MDXTag>
```

**Comment by wooorm** [comment]
Ahh, I get it! Maybe this is something for [`mdx-ast-to-mdx-hast.js`](https://github.com/mdx-js/mdx/blob/master/packages/mdx/mdx-ast-to-mdx-hast.js). Or that can be done by providing a custom handler, that wrap the default function?

If we add it to props here, it’ll show up in HTML as well, so `<code meta="..." class="language-js">...` etc, so that’s not good.

We could add it to [`.data`](https://github.com/syntax-tree/unist#data), but it’s a bit weird to do it for just one key. Maybe we need to do the same for `list.loose`, `listItem.checked`, etc, all the other mdast keys?

**Comment by ChristopherBiscardi** [comment]
I took the custom handler approach in https://github.com/mdx-js/mdx/pull/257 which worked well. Going to close this since it was about the specific instance of code block infostrings.

Not sure if the other metadata (.checked, etc) warrants inclusion in data or not, but happy to work on it if so.
